package handler
import _ "IginServer/web/handler/api/auth"
import _ "IginServer/web/handler/api"
import _ "IginServer/web/handler/api/product"
import _ "IginServer/web/handler/api/sms"
import _ "IginServer/web/handler/api/weixin"
import _ "IginServer/web/handler/test"
import _ "IginServer/web/handler/tranca/admin/auth"
import _ "IginServer/web/handler/tranca/admin"
import _ "IginServer/web/handler/tranca/admin/order"
import _ "IginServer/web/handler/tranca/admin/product"
import _ "IginServer/web/handler/tranca/admin/user"
import _ "IginServer/web/handler/tranca/admin/weixin"